name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          apt-get update
          apt-get install -y zip
      - name: Package zip file
        run: |
          zip -r xklazy-${{ github.ref }}.zip data pack.mcmeta

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/release-action@v1
        with:
          files: |
            xklazy-${{ github.event.release.tag_name }}.zip
          api_key: ${{ secrets.GITHUB_TOKEN }}